language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

cache:
    directories:
    - vendor/

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - composer self-update -n
    - composer install --dev -n

script:
    - vendor/bin/phpunit --coverage-clover clover.xml --bootstrap vendor/autoload.php tests/

after_script:
    - composer require --dev "satooshi/php-coveralls dev-master"
    - vendor/bin/coveralls -n -v

